environment:
    # Enforce sequential JIT'ing of files for controlled memory usage.
    HILTI_JIT_SEQUENTIAL: 1

    # Images for macOS
    IMAGE_MACOS_BIG_SUR:  big-sur-base
    IMAGE_MACOS_CATALINA: catalina-base

zkg_ubuntu_task:
  timeout_in: 120m
  container:
    dockerfile: ci/Dockerfile
    cpu: 4
    memory: 12G

  prepare_script:
    # --force avoids prompts
    - zkg install --force --skiptests spicy-plugin

  test_script:
    - zkg test .

  install_script:
    # --force avoids prompts, --skiptests because tests ran already
    - zkg install --force --skiptests .

  check_script:
    - zeek -NN _Zeek::Spicy | grep -q ANALYZER_SPICY_TFTP
    - zeek -NN _Zeek::Spicy | grep Analyzer
    - (cd /tmp && zeek -r ${CIRRUS_WORKING_DIR}/tests/Traces/tftp_rrq.pcap local && test -e tftp.log && grep rfc1350.txt tftp.log)

  always:
      stderr_script: ./ci/show-zkg-stderr

zkg_macos_task:
  timeout_in: 120m

  osx_instance:
    image: $IMAGE_MACOS_BIG_SUR

  env:
    PATH: /opt/spicy/bin:${PATH}

  install_zeek_script:
    - brew install zeek

  install_spicy_script:
    - brew tap zeek/zeek
    - brew install spicy --HEAD

  prepare_script:
    - pip3 install zkg btest
    - zkg refresh
    - zkg autoconfig && echo "@load packages" >>"$(zeek-config --site_dir)"/local.zeek
    # --force avoids prompts
    - zkg install --force --skiptests spicy-plugin

  test_script:
    - zkg test .

  install_script:
    # --force avoids prompts, --skiptests because tests ran already
    - zkg install --force --skiptests .

  check_script:
    - zeek -NN _Zeek::Spicy | grep -q ANALYZER_SPICY_TFTP
    - zeek -NN _Zeek::Spicy | grep Analyzer
    - (cd /tmp && zeek -r ${CIRRUS_WORKING_DIR}/tests/Traces/tftp_rrq.pcap local && test -e tftp.log && grep rfc1350.txt tftp.log)

  always:
      stderr_script: ./ci/show-zkg-stderr
